### ISSUE TITLE
Blood Merlot (Maybe Blood Potions)

### ISSUE THREAD

**Issue by JeraSpites** [skythebro/PotionsHaveContainers#1]
Blood Merlot does not return a bottle.  (I assume blood potions do not as well.)  Also, is there a way we can toggle the ability to get a bottle back if we fill a ton of bottles with water, and want to use them to make blood potions/blood merlot?  If not, can it be added?  Thanks for reading this, and my apologies if I am asking too much.

**Comment by skythebro** [comment]
I'll have to find a different method to harmony patch because the BuffSystem_Spawn_Server hook I'm using now doesn't get triggered when using a water bottle or a blood potion(blood merlot). I'm going to look into it though. Thanks for bringing it up!

**Comment by skythebro** [comment]
I already have some good news, I found a new method I can patch into that detects the drinking of blood potions and water bottles. Not promising anything yet but could be I can use this.

**Comment by skythebro** [comment]
> Also, is there a way we can toggle the ability to get a bottle back if we fill a ton of bottles with water, and want to use them to make blood potions/blood merlot? If not, can it be added? Thanks for reading this, and my apologies if I am asking too much.

Can you explain this in a bit more detail I don't really understand what you mean.

**Comment by skythebro** [comment]
> Blood Merlot does not return a bottle. (I assume blood potions do not as well.) 

I just got the system working and now both Blood Merlot and blood potions return the bottle on use. The same for the Water canteen and bottle but due to a limitation in the AbilityGroup component I can only return a canteen or a bottle for both (the PrefabGUID of the bottle and canteen are the same because water doesn't have any higher tier). What I mean by this is if you drink a canteen it will give back a canteen and if you drink a bottle it will also give back a canteen now. I could alter it to the opposite where canteen and bottle will return bottle but that would be overpowered because it would be basically turning a canteen into a bottle for free.
